title: "Team Zyberia"
keywords: "Game, Zyberia, Zyber, Team Zyberia"
description: " Human, Developer, also Gamer."
url: "https://teamzyberia.github.io"

permalink: pretty

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
